# Generated by Django 3.0.3 on 2020-03-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200318_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
